# Generated by Django 3.2.8 on 2022-01-14 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asdascrape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=15)),
                ('item_name', models.CharField(max_length=50)),
                ('item_image', models.ImageField(default='default.jpg', upload_to='scrapedimages/asda')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unit_price', models.CharField(max_length=20)),
                ('item_searched', models.CharField(max_length=50)),
                ('date_searched', models.DateField(default=django.utils.timezone.now)),
                ('item_url', models.CharField(max_length=75)),
            ],
        ),
    ]
