# Generated by Django 3.2.8 on 2022-01-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdascrape',
            name='item_image',
            field=models.CharField(max_length=55),
        ),
    ]
