# Generated by Django 3.2.8 on 2022-01-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0002_alter_asdascrape_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdascrape',
            name='item_image',
            field=models.ImageField(default='default.jpg', upload_to='scrapedimages'),
        ),
    ]
