# Generated by Django 3.2.8 on 2022-01-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscraper', '0004_auto_20220117_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asdascrape',
            name='item_url',
            field=models.CharField(max_length=255),
        ),
    ]
